<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
ul.table-view.list-inline.xs-center-block > h2.tmargin.tpad.xs-text-center.xs-center-block.clearfix:last-child {
	display:none;
}
.tab-content{
	border-radius: 16px; 
	
}    

/* Main Container Reset */
    #div1.tab-pane {
        background: #fff !important;
        
        
    }

    /* 1. Main Section Header (Contact & Info) */
    #div1 h2.tmargin.tpad {
        
        font-size: 25px;
        font-weight: 700;
        color: #222;
        margin-top: 0 !important;
        padding-bottom: 10px;
	    padding-top: 0px;
        border-bottom: 2px solid #333; 
        text-align: left !important; 
        width: 100%;
        display: block;
    }

    /* 2. Layout Transformation: Stack Columns Vertical */
    /* This overrides the default side-by-side Bootstrap grid to match the screenshot's stacked look */
    #div1 .table-view-group .col-sm-4,
    #div1 .table-view-group .col-sm-8 {
        width: 100% !important;
        float: none !important;
        padding-left: 0 !important;
        padding-right: 0 !important;
        text-align: left !important;
	    padding-top: 0px;
	    padding-bottom: 0px;
    }

    /* 3. Section Labels (Location, Hours, etc.) */
    #div1 .col-sm-4.bold,
    #div1 h2.about-member-blurb {
        
        font-size: 18px;
        font-weight: 700;
        color: #000;
        margin-bottom: 5px;
        margin-top: 20px; /* Space between sections */
        text-transform: capitalize;
    }

    /* 4. Content Values (Address, Times, Text) */
    #div1 .col-sm-8,
    #div1 .froala-data p {
        
        font-size: 18px;
        color: #000;
        line-height: 1.6;
	    font-weight: 200;
        margin-bottom: 10px;
    }

    /* 5. Phone Button Clean-up */
    /* Removes button styling to make it look like plain text */
    #div1 .click-to-call-button {
        background: none !important;
        border: none !important;
        box-shadow: none !important;
        padding: 0 !important;
        margin: 0 !important;
        text-align: left !important;
        font-size: 15px;
        color: #555 !important;
    }
    #div1 .click-to-call-button:hover {
        background: none !important;
        color: #333 !important;
        text-decoration: underline;
    }
    #div1 .click-to-call-button i {
        display: none; /* Hides the phone icon if desired for cleaner look */
    }

   
    #div1 h2.about-member-blurb {
        font-size: 18px !important; /* Matches other subheaders */
        margin-top: 0 !important;
        border: none !important; /* Removes any default borders */
    }

    /* Utilities */
    #div1 .clearfix {
        display: block;
    }
    
    /* Hide unwanted elements generated by system */
    #div1 ul.table-view > h2:last-child {
        display: none !important;
    }
#div1 .table-display-rep_matters{
	background: #fff;
}

#div1 .overview-tab-the-member-address{
	background: #fff;

}

/* Connect with Me - Social Section */
.connect-with-me-wrapper {
    text-align: center;
   
	border-top: 1px solid #EAE0D1;
}

.connect-with-me-box {
    display: inline-block;
    padding: 20px 30px;
    
    border-radius: 6px;
    background: #ffffff;
}

.connect-with-me-box h4 {
    margin-bottom: 14px;
    font-weight: 600;
    
}

.connect-with-me-icons a {
    margin: 0 12px;
    font-size: 24px;
    color: #333;
    transition: all 0.3s ease;
}

.connect-with-me-icons a:hover {
    color: #ff4d4d;
    
	transform: scale(1.1);
}
.member-extra-contact-details {
    margin-top: 6px;
	font-weight: 200;
}

.member-contact-row {
    margin-bottom: 6px;
	font-weight: bold;
}
.member-contact-row a{
	font-weight: normal;
}
